name: Actions workflow
on:
  push:
    branches:
      - v1
jobs:
  actions-run:
    runs-on: ubuntu-latest
    steps:
      - name : list files
        run: |
          pwd
          ls -a
      - name: checkout
        uses: actions/checkout@v1
      - name : list files1
        run: |
          pwd
          ls -a
      - name: simple JS action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Lokesh
      - name: Log Greeting time
        run: echo "${{steps.greet.outputs.time}}"
